ClaimDesk.Web/Models/Claim/ChangeStatusClaimViewModel.cs
using ClaimDesk.Engine.Enums;

namespace ClaimDesk.Web.Models.Claim
{
	public class ChangeStatusClaimViewModel
	{
		public int ClaimId { get; set; }
		public ClaimStatus NewStatus { get; set; }
		public string Reason { get; set; }
	}
}

ClaimDesk.Web/Models/Claim/IndexClaimViewModel.cs
using System;
using System.Collections.Generic;
using ClaimDesk.Engine.DataContainers;
using ClaimDesk.Engine.Enums;

namespace ClaimDesk.Web.Models.Claim
{
	public class IndexClaimViewModel
	{
		public string Title = "Список заявок";
		public DateTime? MinDate { get; set; }
		public DateTime? MaxDate { get; set; }
		public ClaimStatus? Status { get; set; }
		public IEnumerable<ClaimContainer> Claims { get; set; }
	}
}

ClaimDesk.Web/Models/Claim/SaveClaimViewModel.cs
namespace ClaimDesk.Web.Models.Claim
{
	public class SaveClaimViewModel
	{
		public int? Id { get; set; }
		public string Description { get; set; }
	}
}

ClaimDesk.Web/Controllers/ClaimController.cs
using System.Linq;
using System.Web.Mvc;
using ClaimDesk.Engine.Data;
using ClaimDesk.Engine.Domains;
using ClaimDesk.Engine.Enums;
using ClaimDesk.Engine.Services;
using ClaimDesk.Engine.Services.Interfaces;
using ClaimDesk.Web.Models.Claim;

namespace ClaimDesk.Web.Controllers
{
	public class ClaimController : Controller
	{
		private readonly IClaimService _claimService;
		private readonly IRepository<ClaimDomain> _repository = new EfRepository<ClaimDomain>(new ClaimDeskDataContext());

		public ClaimController()
		{
			_claimService = new ClaimService(_repository);
		}

		public ActionResult Index(IndexClaimViewModel model)
		{
			model.Claims = _claimService.GetClaims(model.MinDate, model.MaxDate, model.Status);
			return View(model);
		}

		public ActionResult GetClaimHistory(int claimId)
		{
			var history = _claimService.GetClaimHistory(claimId).ToArray();
			var statuses = history.Last().Status.GetAvailableStatuses().Select(status => new {text = status.GetDescription(), value = status});
			return Json(new {statuses, history}, JsonRequestBehavior.AllowGet);
		}

		public ActionResult Save(SaveClaimViewModel model)
		{
			_claimService.SaveClaim(model.Id, model.Description);
			return RedirectToAction("Index");
		}

		public ActionResult ChangeStatus(ChangeStatusClaimViewModel model)
		{
			_claimService.SaveClaim(model.ClaimId, model.NewStatus, model.Reason);
			return RedirectToAction("Index");
		}

		public ActionResult Delete(int id)
		{
			_claimService.DeleteClaim(id);
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			_repository.Dispose();
			base.Dispose(disposing);
		}
	}
}

ClaimDesk.Web/Views/Claim/Index.cshtml
@using ClaimDesk.Engine.Enums
@using ClaimDesk.Web.Models.Claim
@model ClaimDesk.Web.Models.Claim.IndexClaimViewModel
@{
	ViewBag.Title = Model.Title;
}
<h2>@Model.Title</h2>

<p>
	@using (Html.BeginForm("Index", "Claim", null, FormMethod.Post, new {@class = "form-inline"}))
	{
		<div class="form-group">
			Заявки c
		</div>
		<div class="form-group">
			@Html.EditorFor(model => model.MinDate, new {htmlAttributes = new {@class = "form-control", type = "date"}})
		</div>
		<div class="form-group">
			Заявки по
		</div>
		<div class="form-group">
			@Html.EditorFor(model => model.MaxDate, new {htmlAttributes = new {@class = "form-control", type = "date"}})
		</div>
		<div class="form-group">
			Статус заявки
		</div>
		@Html.DropDownListFor(model => model.Status,
			((ClaimStatus[]) Enum.GetValues(typeof (ClaimStatus))).Select(status => new SelectListItem {Value = status.ToString(), Text = status.GetDescription()}),
			"Выберите статус", new {@class = "form-control"})
		<button type="submit" class="btn btn-primary">
			<span class="glyphicon glyphicon-search"></span> Поиск
		</button>
	}
</p>

<p>
	<button type="button" class="btn btn-success" onclick="showCreateModal()">Создать новую</button>
</p>

<table class="table table-bordered table-hover">
	<thead>
	<tr class="info">
		<th>Ид</th>
		<th>Дата создания</th>
		<th>Описание</th>
		<th>Статус</th>
		<th>Дата установки статуса</th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	@foreach (var claim in Model.Claims)
	{
		<tr>
			<td>
				@claim.Id
			</td>
			<td>@claim.CreationDate</td>
			<td>
				<span id="desc-@claim.Id">@claim.Description</span>
				<button class="btn btn-link pull-right" onclick="showUpdateModal(@claim.Id, $('#desc-@claim.Id').text())">
					<span class="glyphicon glyphicon-pencil"></span>
				</button>
			</td>
			<td class="row">
				<button class="btn btn-link pull-right" onclick="showCommentModal(@claim.Id)">
					@claim.Status.GetDescription()
				</button>
			</td>
			<td>@claim.СhangeDate</td>
			<td>
				<a href="@Url.Action("Delete", new {id = claim.Id})" class="btn btn-danger btn-xs" onclick="return confirm('Вы действительно хотите удалить заявку @claim.Id?')">
					<span class="glyphicon glyphicon-remove"></span>
				</a>
			</td>
		</tr>
	}
	</tbody>
</table>

@section scripts
{
	@Html.Partial("_ClaimModal", new SaveClaimViewModel())
	@Html.Partial("_ClaimHistoryModal", new ChangeStatusClaimViewModel())

	<script>
		function showModal(title, id, desc) {
			$("#ClaimModal .modal-title").html(title);
			$("#Id").val(id);
			$("#Description").html(desc);

			$("#ClaimModal").modal("show");
		}

		function showUpdateModal(id, desc) {
			showModal("Редактирование заявки №" + id, id, desc);
		}

		function showCreateModal() {
			showModal("Создание заявки");
		}

		function showCommentModal(id) {
			$.ajax({
				url: "@Url.Action("GetClaimHistory", "Claim")",
				data: {
					claimId: id
				},
				success: function (data) {

					$("#history").empty();
					$.each(data.history, function (index, item) {
						$("#history").append($("<tr></tr>")
							.html("<td>" + item.СhangeDate + "</td>")
							.append("<td>" + item.StatusDescription + "</td>")
							.append("<td>" + item.Reason + "</td>"));
					});

					$("#NewStatus option").remove();
					if (data.statuses.length === 0) {
						$("#NewStatusPanel").hide();
						$("#submitBtn").hide();
					} else {
						$("#NewStatusPanel").show();
						$("#submitBtn").show();

						$.each(data.statuses, function(index, item) {
							$("#NewStatus").append(
								$("<option></option>")
								.text(item.text)
								.val(item.value)
							);
						});
					}
				}
			});
			$("#ClaimId").val(id);

			$("#ClaimHistoryModal").modal("show");
		}
	</script>
}

ClaimDesk.Web/Views/Claim/SaveClaim.cshtml
@model ClaimDesk.Web.Models.Claim.SaveClaimViewModel
@{
	ViewBag.Title = Model.Title;
}

<h2>@Model.Title</h2>
@using (Html.BeginForm("Save", "Claim", null, FormMethod.Post, new { @class = "form-horizontal" }))
{
	@Html.HiddenFor(model => model.Title)
	<div class="form-group">
		<div class="col-md-2 control-label">
			Ид
		</div>
		<div class="col-md-5">
			@Html.DisplayFor(model => model.Claim.Id, new { htmlAttributes = new { @class = "form-control" } })
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2 control-label">
			Дата создания
		</div>
		<div class="col-md-5">
			@Html.DisplayFor(model => model.Claim.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2 control-label">
			Описание
		</div>
		<div class="col-md-2">
			@Html.EditorFor(model => model.Claim.Description, new { htmlAttributes = new { @class = "form-control", min = 14 } })
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2 control-label">
			Статус
		</div>
		<div class="col-md-5">
			1
			@*@Html.DropDownListFor(model => model.Claim.Status, Model.Languages, "Выберите отдел", new {@class = "form-control"})*@
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-2 col-md-offset-2">
			<button type="submit" class="btn btn-primary btn-block">Сохранить</button>
		</div>
		<div class="col-md-2">
			@Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default btn-block" })
		</div>
	</div>
}

ClaimDesk.Web/Views/Claim/_ClaimHistoryModal.cshtml
@model ClaimDesk.Web.Models.Claim.ChangeStatusClaimViewModel

@using (Html.BeginForm("ChangeStatus", "Claim", null, FormMethod.Post, new {@class = "form-horizontal"}))
{
	@Html.HiddenFor(model => model.ClaimId)
	<div class="modal fade" id="ClaimHistoryModal" tabindex="-1">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"></button>
					<h4 class="modal-title">Состояние заявки</h4>
				</div>
				<div class="modal-body">
					<div class="form-group" id="NewStatusPanel">
						<label class="control-label">Новый статус:</label>
						<select id="NewStatus" name="NewStatus" class="form-control"></select>
						@Html.TextAreaFor(model => model.Reason, new {@class = "form-control", placeholder = "Основание смены статуса", required = "true" })
					</div>
					<table class="table table-bordered">
						<thead>
							<tr class="info">
								<th>Дата установки статуса</th>
								<th>Статус</th>
								<th>Причина</th>
							</tr>
						</thead>
						<tbody id="history">
						</tbody>
					</table>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
					<button class="btn btn-primary" id="submitBtn" type="submit">Сохранить</button>
				</div>
			</div>
		</div>
	</div>
}

ClaimDesk.Web/Views/Claim/_ClaimModal.cshtml
@model ClaimDesk.Web.Models.Claim.SaveClaimViewModel

@using (Html.BeginForm("Save", "Claim", null, FormMethod.Post, new {@class = "form-horizontal"}))
{
	@Html.HiddenFor(model => model.Id)
	<div class="modal fade" id="ClaimModal" tabindex="-1">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"></button>
					<h4 class="modal-title"></h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label class="control-label">Описание заявки:</label>
						@Html.TextAreaFor(model => model.Description, new {@class = "form-control"})
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
					<button type="submit" class="btn btn-primary">Сохранить</button>
				</div>
			</div>
		</div>
	</div>
}

ClaimDesk.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - Заявки</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			@Html.ActionLink("Заявки", "Index", "Claim", new {area = ""}, new {@class = "navbar-brand"})
		</div>
	</div>
</div>
<div class="container body-content">
	@RenderBody()
</div>
<footer class="text-center text-muted">
	<p>&copy; @DateTime.Now.Year - ClaimDesk</p>
</footer>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>